# Generated by ChatGPT

import json

def convert_to_vscode_snippet(file_path: str):
    # 读取文件中的所有行
    with open(file_path, 'r', encoding='utf-8') as file:
        lines = file.readlines()

    # 转换为VSCode片段格式
    snippet_body = [line.rstrip() for line in lines]
    snippet_body += ['']  # 添加空行

    return json.dumps(snippet_body, indent=4)

# 替换为您的代码文件路径
file_path = 'template.py'

print(convert_to_vscode_snippet(file_path))
